# Generated by Django 2.0.5 on 2018-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.CharField(max_length=30)),
                ('naz', models.CharField(max_length=30)),
            ],
        ),
    ]
